# Generated by Django 2.0.4 on 2018-04-25 20:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('header', models.CharField(db_index=True, max_length=8)),
                ('dlc', models.SmallIntegerField(verbose_name='Data Length Code')),
                ('payload', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('timestamp',),
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GpsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('groundspeed', models.DecimalField(decimal_places=14, max_digits=17)),
                ('truecourse', models.DecimalField(decimal_places=14, max_digits=17)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('timestamp',),
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puc',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gpsmessage',
            name='puc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_messages', related_query_name='gps_message', to='pucs.Puc'),
        ),
        migrations.AddField(
            model_name='canmessage',
            name='puc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_messages', related_query_name='can_message', to='pucs.Puc'),
        ),
    ]
